extends Node

enum FACTIONS {
	COAST_DWARFS,
	MT_DWARFS,
	RIDGE_DWARFS,
	FIRE_DWARFS,
	FOREST_DWARFS,
	RAVINE_DWARFS,

	DARK_BEASTS,

	BAY_HUMANS,
	RAVINE_HUMANS,
	FOREST_HUMANS,
	CASTLE_HUMANS,
	TROPIC_HUMANS,
	COAST_HUMANS,

	HEART_OF_THE_NATURE,

	DESERT_EMPIRE,

	NORD_ELVES,
	MAINLAND_ELVES,
	BAY_ELVES,
	COAST_ELVES,
}

var FACTIONS_TEXT: Dictionary[FACTIONS, String] = {
	FACTIONS.COAST_DWARFS: "COAST_DWARFS",
	FACTIONS.MT_DWARFS: "MT_DWARFS",
	FACTIONS.RIDGE_DWARFS: "RIDGE_DWARFS",
	FACTIONS.FIRE_DWARFS: "FIRE_DWARFS",
	FACTIONS.FOREST_DWARFS: "FOREST_DWARFS",
	FACTIONS.RAVINE_DWARFS: "RAVINE_DWARFS",

	FACTIONS.DARK_BEASTS: "DARK_BEASTS",

	FACTIONS.BAY_HUMANS: "BAY_HUMANS",
	FACTIONS.RAVINE_HUMANS: "RAVINE_HUMANS",
	FACTIONS.FOREST_HUMANS: "FOREST_HUMANS",
	FACTIONS.CASTLE_HUMANS: "CASTLE_HUMANS",
	FACTIONS.TROPIC_HUMANS: "TROPIC_HUMANS",
	FACTIONS.COAST_HUMANS: "COAST_HUMANS",

	FACTIONS.HEART_OF_THE_NATURE: "HEART_OF_THE_NATURE",
	
	FACTIONS.DESERT_EMPIRE: "DESERT_EMPIRE",

	FACTIONS.NORD_ELVES: "NORD_ELVES",
	FACTIONS.MAINLAND_ELVES: "MAINLAND_ELVES",
	FACTIONS.BAY_ELVES: "BAY_ELVES",
	FACTIONS.COAST_ELVES: "COAST_ELVES",
}

var _relations: Dictionary = {}

func _get_key(f1: FACTIONS, f2: FACTIONS) -> String:
	var keys = [f1, f2]
	keys.sort()
	return "%s_%s" % [keys[0], keys[1]]

func set_relation(f1: FACTIONS, f2: FACTIONS, value: int) -> void:
	if f1 == f2: return
	_relations[_get_key(f1, f2)] = clampi(value, -100, 100)

func get_relation(f1: FACTIONS, f2: FACTIONS) -> int:
	if f1 == f2: return 100
	return _relations.get(_get_key(f1, f2), 0)

# func _ready() -> void:
# 	set_relation(FACTIONS.SAN, FACTIONS.RIK, -24)
# 	set_relation(FACTIONS.SAN, FACTIONS.ROMBUS, -25)
# 	set_relation(FACTIONS.SAN, FACTIONS.PARADOX, 80)

# 	set_relation(FACTIONS.RIK, FACTIONS.ROMBUS, 100)
# 	set_relation(FACTIONS.RIK, FACTIONS.PARADOX, 0)

# 	set_relation(FACTIONS.ROMBUS, FACTIONS.PARADOX, -100)
