extends Node

enum TEAMS {
	BLUE = 1 << 0,
	RED = 1 << 1,
	GREEN = 1 << 2,
	YELLOW = 1 << 3,
}

enum TEAM_MAPPING {
	BLUE = TEAMS.RED | TEAMS.YELLOW,
	RED = TEAMS.BLUE | TEAMS.GREEN,
	GREEN = TEAMS.RED | TEAMS.YELLOW,
	YELLOW = TEAMS.RED | TEAMS.BLUE | TEAMS.GREEN,
}

enum REGION_ACTION_TYPE {
	NONE,
	HIRE_ARMY,
}

const DEFAULT_REGION_ACTIONS: Array[REGION_ACTION_TYPE] = [
	REGION_ACTION_TYPE.HIRE_ARMY,
	REGION_ACTION_TYPE.HIRE_ARMY,
	REGION_ACTION_TYPE.HIRE_ARMY,
]
