extends Node

enum TEAMS {
	BLUE = 1 << 0,
	RED = 1 << 1,
	GREEN = 1 << 2,
	YELLOW = 1 << 3,
}

enum TEAM_MAPPING {
	BLUE = TEAMS.RED | TEAMS.YELLOW,
	RED = TEAMS.BLUE | TEAMS.GREEN,
	GREEN = TEAMS.RED | TEAMS.YELLOW,
	YELLOW = TEAMS.RED | TEAMS.BLUE | TEAMS.GREEN,
}
