extends Node

enum TEAMS {
	BLUE = 1 << 0,
	RED = 1 << 1,
	GREEN = 1 << 2,
	YELLOW = 1 << 3,
}

enum TEAM_MAPPING {
	BLUE = TEAMS.RED | TEAMS.YELLOW,
	RED = TEAMS.BLUE | TEAMS.GREEN,
	GREEN = TEAMS.RED | TEAMS.YELLOW,
	YELLOW = TEAMS.RED | TEAMS.BLUE | TEAMS.GREEN,
}

const TEAMS_MAPPING_TO_MAPPINGS: Dictionary[TEAMS, TEAM_MAPPING] = {
	TEAMS.BLUE: TEAM_MAPPING.BLUE,
	TEAMS.RED: TEAM_MAPPING.RED,
	TEAMS.GREEN: TEAM_MAPPING.GREEN,
	TEAMS.YELLOW: TEAM_MAPPING.YELLOW,
}

enum REGION_ACTION_TYPE {
	NONE,
	HIRE_ARMY,
	ATTACK,
}

const DEFAULT_REGION_ACTIONS: Array[REGION_ACTION_TYPE] = [
	REGION_ACTION_TYPE.HIRE_ARMY,
	REGION_ACTION_TYPE.ATTACK,
]

# TODO: replace with normal localization tool
const ACTIONS_TEXT: Dictionary[REGION_ACTION_TYPE, String] = {
	REGION_ACTION_TYPE.NONE: "This is a bug",
	REGION_ACTION_TYPE.HIRE_ARMY: "Hire army",
	REGION_ACTION_TYPE.ATTACK: "Attack",
}
